# -*- coding: utf-8 -*-
"""Turn `backend/.env` into a Cloud Run `--env-vars-file`, without ever printing a secret.

Cloud Run takes configuration as environment variables, which is exactly the second half of
config.py's file-then-environment lookup (D-031). The alternative — `--set-env-vars` with the
values inline — puts every key into the shell history and into whatever transcript is
watching, so this writes a YAML file instead and prints only variable *names*.

    python scripts/cloudrun_env.py                  # → backend/.env.cloudrun.yaml (gitignored)
    python scripts/cloudrun_env.py --out /tmp/x.yaml
    python scripts/cloudrun_env.py --set ALLOWED_ORIGINS=https://sarjy.vercel.app

The variable list comes from `.env.example`, so a variable added there but forgotten in a
deploy shows up as PENDING rather than as a mystery 500 an hour later (the same reasoning as
the smoke test, D-021).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from dotenv import dotenv_values

BACKEND_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = BACKEND_DIR / ".env"
EXAMPLE_PATH = BACKEND_DIR / ".env.example"
DEFAULT_OUT = BACKEND_DIR / ".env.cloudrun.yaml"


def yaml_quote(value: str) -> str:
    """Single-quoted YAML — the only escape inside is a doubled quote."""
    return "'" + value.replace("'", "''") + "'"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--set",
        action="append",
        default=[],
        metavar="NAME=VALUE",
        help="Override or add a variable (repeatable). Deploy-only values live here.",
    )
    args = parser.parse_args()

    expected = [name for name in dotenv_values(EXAMPLE_PATH)]
    values = {k: (v or "").strip() for k, v in dotenv_values(ENV_PATH).items()}

    for override in args.set:
        if "=" not in override:
            print(f"--set expects NAME=VALUE, got {override!r}", file=sys.stderr)
            return 2
        name, _, value = override.partition("=")
        values[name.strip()] = value.strip()
        if name.strip() not in expected:
            expected.append(name.strip())

    written, pending = [], []
    lines = ["# Generated by scripts/cloudrun_env.py — never commit this file.\n"]
    for name in expected:
        value = values.get(name, "")
        if value:
            lines.append(f"{name}: {yaml_quote(value)}\n")
            written.append(name)
        else:
            pending.append(name)

    args.out.write_text("".join(lines), encoding="utf-8")
    args.out.chmod(0o600)

    print(f"wrote {len(written)} variables → {args.out}")
    print("  set:     " + ", ".join(written))
    if pending:
        print("  PENDING: " + ", ".join(pending) + "  (empty in .env — deployed as unset)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
